language: python
python:
  - "3.6"
install:
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install r-base
  - pip install --no-cache-dir -r requirements.txt
  - python setup.py install
notifications:
    slack: economydivision:FQ4SZvoepYndcrFjmzYnAtNC
